---
# token is the admin_token in keystone.conf
token:    ADMIN
endpoint: http://keystone:35357/v2.0

default tenant:
    name:        tenant
    description: Default Tenant

# This is the admin user
default user:
    name:     admin
    password: password

# See: http://docs.openstack.org/essex/openstack-compute/install/content/setting-up-tenants-users-and-roles.html
service users:
    - name:     glance
      password: glancepw

    - name:     nova
      password: novapw

    - name:     ec2
      password: ec2pw

    - name:     swift
      password: swiftpass

    - name:     neutron
      password: neutronpw

    - name:     cinder
      password: cinderpw

    - name:     ceilometer
      password: ceilometerpw

    - name:     heat
      password: heatpw

# See: http://docs.openstack.org/essex/openstack-compute/install/content/keystone-service-endpoint-create.html
services and endpoints:
    - name:         keystone
      type:         identity
      description:  Keystone Identity Service
      region:       RegionOne
      publicurl:    http://keystone:5000/v2.0
      internalurl:  http://keystone:5000/v2.0
      adminurl:     http://keystone:35357/v2.0

    - name:         nova
      type:         compute
      description:  Nova Compute Service
      region:       RegionOne
      publicurl:    http://nova-api:8774/v2/%(tenant_id)s
      internalurl:  http://nova-api:8774/v2/%(tenant_id)s
      adminurl:     http://nova-api:8774/v2/%(tenant_id)s

    - name:         glance
      type:         image
      description:  Glance Image Service
      region:       RegionOne
      publicurl:    http://glance-api:9292/v1
      internalurl:  http://glance-api:9292/v1
      adminurl:     http://glance-api:9292/v1

    - name:         ec2
      type:         ec2
      description:  EC2 Compatibility Layer
      region:       RegionOne
      publicurl:    http://nova-api:8773/services/Cloud
      internalurl:  http://nova-api:8773/services/Cloud
      adminurl:     http://nova-api:8773/services/Admin

    - name:         swift
      type:         object-store
      description:  Swift Object Storage Service
      region:       RegionOne
      publicurl:    http://swift:8888/v1/AUTH_%(tenant_id)s
      internalurl:  http://swift:8888/v1/AUTH_%(tenant_id)s
      adminurl:     http://swift:8888/v1

    - name:         neutron
      type:         network
      description:  OpenStack Networking Service
      region:       RegionOne
      publicurl:    http://neutron:9696
      internalurl:  http://neutron:9696
      adminurl:     http://neutron:9696

    - name:         cinder
      type:         volume
      description:  OpenStack Volume Service
      region:       RegionOne
      publicurl:    http://cinder-api:8776/v1/%(tenant_id)s
      internalurl:  http://cinder-api:8776/v1/%(tenant_id)s
      adminurl:     http://cinder-api:8776/v1/%(tenant_id)s

    - name:         ceilometer
      type:         telemetry
      description:  OpenStack Telemetry Service
      region:       RegionOne
      publicurl:    http://ceilometer:8777
      internalurl:  http://ceilometer:8777
      adminurl:     http://ceilometer:8777

    - name:         heat
      type:         orchestration
      description:  OpenStack Heat Service
      region:       RegionOne
      publicurl:    http://heat:8004/v1/%(tenant_id)s
      internalurl:  http://heat:8004/v1/%(tenant_id)s
      adminurl:     http://heat:8004/v1/%(tenant_id)s

    - name:         heat-cfn
      type:         cloudformation
      description:  OpenStack Heat Cloudformation
      region:       RegionOne
      publicurl:    http://heat:8000/v1
      internalurl:  http://heat:8000/v1
      adminurl:     http://heat:8000/v1

